# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring.application.name: admin-portal

spring:
    aop:
      proxy-target-class: true
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

targets.uaa: http://localhost:8080/uaa

security.oauth2:
  client:
    accessTokenUri: ${targets.uaa}/oauth/token
    userAuthorizationUri: ${targets.uaa}/oauth/authorize
    clientId: admin-portal
    clientSecret: secret
    # scope: openid,menu.read,menu.write,order.admin
    scope: openid,foo.read,foo.write,foo.admin
  resource:
    user-info-uri: ${targets.uaa}/userinfo
    jwt.keyUri: ${targets.uaa}/token_key


zuul:
  routes:
    resource:
      path: /api/foos/**
      service-id: foo-service
      strip-prefix: false
    user:
      path: /api/user/**
      url: http://localhost:8080/uaa/userinfo

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: foo@localhost
    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: 104b75801be0a441fc0fc643149279aaeecf5b37
    swagger:
        title: foo API
        description: foo API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
