spring.application.name: foo-service

server.port: 8083

security:
  basic:
    enabled: false

targets.uaa: http://localhost:8080/uaa

spring.oauth2:
  resource:
    jwt.keyUri: ${targets.uaa}/token_key

spring.jpa.hibernate.ddl-auto: update
